# Generated by Django 4.1.2 on 2022-10-24 11:13

from django.db import migrations

def create_data(apps, schema_editor):
    Location = apps.get_model('programme', 'Location')
    Location(name="Conference Room A", description="First room on the right").save()

    Mod = apps.get_model('programme', 'Mod')
    Mod(name="Juliet Star", email='jstar@example.com').save()

    Item = apps.get_model('programme', 'Item')
    Item(title="Opening Ceremony", description="Welcome to the conference!").save()

class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
