# Generated by Django 4.1.2 on 2022-10-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_remove_item_location_remove_item_moderator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='programme.location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='programme.mod'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
