# Generated by Django 4.1.2 on 2022-10-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_alter_item_location_alter_item_moderator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
