# Generated by Django 4.1.2 on 2022-10-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_alter_item_time'),
    ]

    operations = [
        migrations.RenameModel('Mod', 'Attendee'),
    ]
