# Generated by Django 4.1.2 on 2022-10-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0006_auto_20221024_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='status',
            field=models.CharField(choices=[('guest', 'Guest'), ('member', 'Member')], default='member', max_length=6),
        ),
    ]
